name: Validate with hassfest
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
jobs:
  validate:
    runs-on: "ubuntu-latest"
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
    steps:
      - uses: "actions/checkout@v4"
      - name: Log in to GitHub Container Registry
        uses: "docker/login-action@v3"
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Validate with hassfest
        uses: "home-assistant/actions/hassfest@master"
