name: Validate with hassfest
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: Run hassfest (custom integration)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/github/workspace \
            ghcr.io/home-assistant/hassfest \
            --core-path /github/workspace \
            --integration-path /github/workspace/custom_components/skydark_calendar
